config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  get 'movies/update_any' => 'movies#update_any', as: :update_any
  put 'movies/update_any' => 'movies#update_post', as: :update_post
  get 'movies/delete_any' => 'movies#delete_any', as: :delete_any
  delete 'movies/delete_any' => 'movies#delete_done', as: :delete_done

  resources :movies
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
    def self.all_ratings
        @all_ratings = ['G','PG','PG-13','R','NC-17']
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end
  
  def delete_any
  end
  
  def delete_done
    if (params[:movie][:title] != '')
      @movie = Movie.find_by_title(params[:movie][:title])
      if (@movie == nil)
        flash[:notice] = "#{params[:movie][:title]} does not exist."
      else
        @movie.destroy
        flash[:notice] = "Movie '#{params[:movie][:title]}' deleted."
      end
    end
    if (params[:movie][:rating] != '')
      Movie.where('rating = ?', params[:movie][:rating]).each do |mov|
        mov.destroy
      end
      flash[:notice] = "Movies with Rating '#{params[:movie][:rating]}' deleted."
    end
    redirect_to movies_path#(@movie)
  end
  
  def update_any
  end
  
  def update_post
    @movie = Movie.find_by_title(params[:movie][:in_movie])
    if (@movie == nil)
      flash[:notice] = "#{params[:movie][:in_movie]} does not exist."
    else
      @movie.update_attributes!(movie_params)
      flash[:notice] = "#{params[:movie][:title]} was successfully updated."
    end
    redirect_to movies_path#(@movie)
  end
  
  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @all_ratings = Movie.all_ratings
    
    if ((params[:sort_by] == 'title') || (params[:sort_by] == 'release_date'))
      params[:ratings] = session[:ratings]
      @ratings = params[:ratings]
      session[:sort_by] = params[:sort_by]
      @movies = Movie.where(:rating => params[:ratings].keys).order(params[:sort_by])
      if (params[:sort_by] == 'title')
        @style_title = 'hilite'
      elsif (params[:sort_by] == 'release_date')
        @style_release = 'hilite'
      end
    elsif (!(params[:ratings].nil?))
      params[:sort_by] = session[:sort_by]
      @ratings = params[:ratings]
      session[:ratings] = params[:ratings]
      if ((params[:sort_by] == 'title') || (params[:sort_by] == 'release_date'))
        @movies = Movie.where(:rating => params[:ratings].keys).order(params[:sort_by])
        if (params[:sort_by] == 'title')
          @style_title = 'hilite'
        elsif (params[:sort_by] == 'release_date')
          @style_release = 'hilite'
        end
      else
        @movies = Movie.where(:rating => params[:ratings].keys)
      end
    else
      @ratings =  {'G'=>true,'PG'=>true,'PG-13'=>true,'R'=>true,'NC-17'=>true}
      @movies = Movie.all
      session[:ratings] = @ratings
      session[:sort_by] = params[:sort_by]
    end
    
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

app/views/movies/delete_any.html.haml
%h1 Delete Movies

= form_tag delete_done_path, :method => :delete do

  = label :movie, :title, 'Select a Movie:'
  = text_field :movie, 'title'

  = label :movie, :rating, 'And/Or a Rating'
  = select :movie, :rating, ['','G','PG','PG-13','R','NC-17']

  = submit_tag 'Delete Movie'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get do
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", true, @ratings[rating]?true:false
  = submit_tag 'Refresh'

%table#movies
  %thead
    %tr
      %th= link_to 'Movie Title', movies_path(:sort_by=>'title'), :class=>@style_title
      %th Rating
      %th= link_to 'Release Date', movies_path(:sort_by=>'release_date'), :class=>@style_release
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path
= link_to 'Update a movie', update_any_path
= link_to 'Delete a movie', delete_any_path

app/views/movies/update_any.html.haml
%h1 Edit Existing Movie

= form_tag update_post_path, :method => :put do

  = label :movie, :title, 'Existing Movie Title'
  = text_field :movie, 'in_movie'

  = label :movie, :title, 'New Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'New Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'New Release Date'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'